export const dashboardMock = {
  kpis: [
    {
      id: 'couriers',
      label: 'Entregadores ativos',
      value: '12',
      meta: '9 em rota e 3 em base operacional',
      badgeText: '+8%',
      badgeClass: 'ui-badge--success',
      tone: 'cyan',
    },
    {
      id: 'orders',
      label: 'Pedidos em andamento',
      value: '27',
      meta: 'Maior concentracao entre 19h e 21h',
      badgeText: 'pico',
      badgeClass: 'ui-badge--warning',
      tone: 'amber',
    },
    {
      id: 'cash',
      label: 'Fechamento parcial',
      value: 'R$ 4.280',
      meta: 'Comissao projetada de R$ 428 no turno',
      badgeText: 'online',
      badgeClass: 'ui-badge--info',
      tone: 'blue',
    },
    {
      id: 'issues',
      label: 'Ocorrencias criticas',
      value: '03',
      meta: '1 maquininha, 2 atrasos de retorno',
      badgeText: 'alerta',
      badgeClass: 'ui-badge--danger',
      tone: 'red',
    },
  ],
  charts: {
    weeklyDeliveries: [
      { label: 'Seg', value: 48 },
      { label: 'Ter', value: 54 },
      { label: 'Qua', value: 49 },
      { label: 'Qui', value: 63 },
      { label: 'Sex', value: 71 },
      { label: 'Sab', value: 89 },
      { label: 'Dom', value: 58 },
    ],
    hourlyOrders: [
      { label: '17h', value: 8 },
      { label: '18h', value: 14 },
      { label: '19h', value: 23 },
      { label: '20h', value: 27 },
      { label: '21h', value: 19 },
      { label: '22h', value: 12 },
    ],
  },
  operations: {
    activeShift: [
      {
        id: '1',
        name: 'Moizes',
        role: 'Noite',
        machine: 'Maq. 03',
        statusLabel: 'Em rota',
        statusClass: 'ui-badge--info',
      },
      {
        id: '2',
        name: 'Tito',
        role: 'Noite',
        machine: 'Maq. 05',
        statusLabel: 'Retorno',
        statusClass: 'ui-badge--success',
      },
      {
        id: '3',
        name: 'Camila',
        role: 'Tarde',
        machine: 'Maq. 08',
        statusLabel: 'Atraso',
        statusClass: 'ui-badge--warning',
      },
    ],
    pending: [
      {
        id: 'p1',
        title: 'Troco pendente',
        description: 'R$ 120 aguardando conferencia no caixa 02.',
        badgeText: 'troco',
        badgeClass: 'ui-badge--warning',
      },
      {
        id: 'p2',
        title: 'Vale aberto',
        description: '2 adiantamentos seguem sem baixa no fechamento.',
        badgeText: 'financeiro',
        badgeClass: 'ui-badge--danger',
      },
      {
        id: 'p3',
        title: 'Checklist de maquininha',
        description: '1 dispositivo sem conferencia desde 18:40.',
        badgeText: 'hardware',
        badgeClass: 'ui-badge--info',
      },
    ],
    closing: [
      { id: 'c1', label: 'Entregas', value: '86' },
      { id: 'c2', label: 'Comissao', value: 'R$ 428' },
      { id: 'c3', label: 'Vales', value: 'R$ 160' },
      { id: 'c4', label: 'Trocos', value: 'R$ 120' },
    ],
  },
};
