export const FIRESTORE_COLLECTIONS = {
  users: 'users',
  stores: 'stores',
  couriers: 'couriers',
  manualModules: 'manual_modules',
  externalOrders: 'external_orders',
  externalOrderEvents: 'external_order_events',
  externalOrderTracking: 'external_order_tracking',
  integrationLogs: 'integration_logs',
  integrationMerchants: 'integration_merchants',
  orders: 'orders',
  sales: 'sales',
  products: 'products',
  inventoryItems: 'inventory_items',
  inventoryMovements: 'inventory_movements',
  customers: 'customers',
  financialEntries: 'financial_entries',
  financialClosures: 'financial_closures',
  financialOccurrences: 'financial_occurrences',
  auditLogs: 'audit_logs',
  backupLogs: 'backup_logs',
  backupSnapshots: 'backup_snapshots',
  settings: 'settings',
  notificationsPreferences: 'notifications_preferences',
  reports: 'reports',
}

export const firestoreDataModel = {
  users: {
    path: 'users/{userId}',
    fields: ['email', 'role', 'tenantId', 'storeIds', 'defaultStoreId', 'status'],
  },
  stores: {
    path: 'stores/{storeId}',
    fields: ['name', 'tenantId', 'status', 'timezone'],
  },
  couriers: {
    path: 'stores/{storeId}/couriers/{courierId}',
    fields: ['storeId', 'tenantId', 'status', 'name', 'shift', 'vehicle'],
  },
  orders: {
    path: 'stores/{storeId}/orders/{orderId}',
    fields: ['storeId', 'tenantId', 'status', 'origin', 'paymentMethod', 'total'],
  },
  external_orders: {
    path: 'stores/{storeId}/external_orders/{documentId}',
    fields: [
      'storeId',
      'tenantId',
      'source',
      'externalOrderId',
      'merchantId',
      'displayId',
      'customer',
      'items',
      'subtotal',
      'discount',
      'shipping',
      'total',
      'paymentMethod',
      'externalStatus',
      'normalizedStatus',
      'tracking',
      'timeline',
      'sync',
      'createdAt',
      'updatedAt',
    ],
  },
  external_order_events: {
    path: 'stores/{storeId}/external_order_events/{eventId}',
    fields: [
      'storeId',
      'tenantId',
      'source',
      'eventId',
      'externalOrderId',
      'merchantId',
      'eventCode',
      'eventFullCode',
      'eventGroup',
      'salesChannel',
      'metadata',
      'createdAt',
      'processedAt',
    ],
  },
  external_order_tracking: {
    path: 'stores/{storeId}/external_order_tracking/{trackingId}',
    fields: [
      'storeId',
      'tenantId',
      'source',
      'externalOrderId',
      'merchantId',
      'status',
      'label',
      'description',
      'happenedAt',
      'location',
      'eventId',
    ],
  },
  integration_logs: {
    path: 'stores/{storeId}/integration_logs/{logId}',
    fields: [
      'storeId',
      'tenantId',
      'source',
      'merchantId',
      'externalOrderId',
      'scope',
      'level',
      'message',
      'payload',
      'createdAt',
    ],
  },
  integration_merchants: {
    path: 'stores/{storeId}/integration_merchants/{merchantId}',
    fields: [
      'storeId',
      'tenantId',
      'source',
      'merchantId',
      'name',
      'clientId',
      'clientSecret',
      'webhookSecret',
      'webhookUrl',
      'pollingEnabled',
      'webhookEnabled',
      'trackingEnabled',
      'widgetId',
      'widgetMerchantIds',
      'lastPollingAt',
      'lastWebhookAt',
      'lastSyncAt',
      'lastSyncError',
      'status',
    ],
  },
  sales: {
    path: 'stores/{storeId}/sales/{saleId}',
    fields: [
      'storeId',
      'tenantId',
      'orderId',
      'customerId',
      'customerSnapshot',
      'items',
      'subtotal',
      'discount',
      'shipping',
      'total',
      'paymentMethod',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  products: {
    path: 'stores/{storeId}/products/{productId}',
    fields: [
      'storeId',
      'tenantId',
      'status',
      'name',
      'category',
      'price',
      'cost',
      'stock',
      'minimumStock',
    ],
  },
  inventory_items: {
    path: 'stores/{storeId}/inventory_items/{productId}',
    fields: [
      'storeId',
      'tenantId',
      'productId',
      'productName',
      'category',
      'sku',
      'currentStock',
      'minimumStock',
      'updatedAt',
    ],
  },
  inventory_movements: {
    path: 'stores/{storeId}/inventory_movements/{movementId}',
    fields: [
      'storeId',
      'tenantId',
      'productId',
      'productName',
      'movementType',
      'quantity',
      'reason',
      'source',
      'relatedSaleId',
      'previousStock',
      'resultingStock',
      'createdAt',
    ],
  },
  customers: {
    path: 'stores/{storeId}/customers/{customerId}',
    fields: ['storeId', 'tenantId', 'status', 'name', 'phone', 'neighborhood', 'addressLine'],
  },
  financial_entries: {
    path: 'stores/{storeId}/financial_entries/{entryId}',
    fields: [
      'storeId',
      'tenantId',
      'type',
      'source',
      'relatedSaleId',
      'description',
      'amount',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  financial_closures: {
    path: 'stores/{storeId}/financial_closures/{closureId}',
    fields: [
      'storeId',
      'tenantId',
      'cashierName',
      'startDate',
      'endDate',
      'totalIncome',
      'totalExpense',
      'balance',
      'createdAt',
    ],
  },
  financial_occurrences: {
    path: 'stores/{storeId}/financial_occurrences/{occurrenceId}',
    fields: [
      'storeId',
      'tenantId',
      'destinationSector',
      'category',
      'title',
      'reference',
      'amount',
      'cashierName',
      'operatorName',
      'occurredAt',
      'description',
      'printedAt',
      'createdAt',
      'updatedAt',
    ],
  },
  audit_logs: {
    path: 'stores/{storeId}/audit_logs/{auditId}',
    fields: [
      'storeId',
      'tenantId',
      'actor',
      'action',
      'entityType',
      'entityId',
      'description',
      'createdAt',
    ],
  },
  backup_logs: {
    path: 'stores/{storeId}/backup_logs/{backupLogId}',
    fields: [
      'storeId',
      'tenantId',
      'status',
      'mode',
      'reason',
      'syncedScopes',
      'skippedScopes',
      'conflicts',
      'recordsSynced',
      'durationMs',
      'startedAtClient',
      'completedAtClient',
    ],
  },
  backup_snapshots: {
    path: 'stores/{storeId}/backup_snapshots/{scopeId}',
    fields: [
      'storeId',
      'tenantId',
      'scopeId',
      'storageKey',
      'category',
      'recordsCount',
      'recordIds',
      'checksum',
      'operationalDay',
      'updatedAtClient',
      'updatedAtServer',
    ],
  },
  settings: {
    path: 'stores/{storeId}/settings/{settingId}',
    fields: ['storeId', 'tenantId', 'type', 'payload'],
  },
  notifications_preferences: {
    path: 'stores/{storeId}/notifications_preferences/{userId}',
    fields: ['enabled', 'channels', 'types', 'updatedAt', 'updatedBy'],
  },
}
