export const routeDefinitions = [
  {
    path: 'dashboard',
    label: 'Dashboard',
    icon: '01',
    section: 'Principal',
    eyebrow: 'Overview',
    title: 'Radar operacional',
    description: 'Entrada central do sistema com indicadores, alertas e leitura imediata do turno.',
    requiredRoles: ['atendente'],
  },
  {
    path: 'couriers',
    label: 'Entregadores',
    icon: '02',
    section: 'Operacao',
    eyebrow: 'Operacao',
    title: 'Entregadores',
    description: 'Controle de cadastro, disponibilidade, perfil e acompanhamento do time.',
    requiredRoles: ['operador'],
  },
  {
    path: 'schedule',
    label: 'Escala',
    icon: '03',
    section: 'Operacao',
    eyebrow: 'Operacao',
    title: 'Escala do dia',
    description: 'Escala manual dos entregadores por horario de entrada e apoio do turno.',
    requiredRoles: ['operador'],
  },
  {
    path: 'delivery-reading',
    label: 'Leitura',
    icon: '03A',
    section: 'Operacao',
    eyebrow: 'Operacao',
    title: 'Leitura de entregas',
    description: 'Leitura rapida das entregas por codigo, entregador e fechamento do envio.',
    requiredRoles: ['operador'],
  },
  {
    path: 'cash',
    label: 'Caixa',
    icon: '04',
    section: 'Financeiro',
    eyebrow: 'Financeiro',
    title: 'Caixa',
    description: 'Abertura, sangria, suprimento e fechamento do caixa com historico operacional.',
    requiredRoles: ['gerente'],
  },
  {
    path: 'financial-pendings',
    label: 'Pendencias fin.',
    icon: '04A',
    section: 'Financeiro',
    eyebrow: 'Financeiro',
    title: 'Pendencias financeiras',
    description: 'Fila unica de pendencias financeiras para trocos, estornos, cobrancas e ajustes.',
    requiredRoles: ['atendente'],
  },
  {
    path: 'advances',
    label: 'Vales',
    icon: '05',
    section: 'Financeiro',
    eyebrow: 'Financeiro',
    title: 'Vales',
    description: 'Registro, baixa e acompanhamento de adiantamentos do time.',
    requiredRoles: ['operador'],
  },
  {
    path: 'discounts',
    label: 'Descontos',
    icon: '06',
    section: 'Financeiro',
    eyebrow: 'Financeiro',
    title: 'Descontos',
    description: 'Controle de descontos, justificativas e impacto no turno.',
    requiredRoles: ['operador'],
  },
  {
    path: 'change',
    label: 'Trocos',
    icon: '07',
    section: 'Financeiro',
    eyebrow: 'Financeiro',
    title: 'Trocos',
    description: 'Solicitacoes, confirmacoes e pendencias de troco em tempo operacional.',
    requiredRoles: ['operador'],
  },
  {
    path: 'machines',
    label: 'Maquininhas',
    icon: '08',
    section: 'Hardware',
    eyebrow: 'Hardware',
    title: 'Maquininhas',
    description: 'Inventario, checklist e status operacional do parque de maquininhas.',
    requiredRoles: ['operador'],
  },
  {
    path: 'machine-history',
    label: 'Hist. maquininhas',
    icon: '09',
    section: 'Hardware',
    eyebrow: 'Hardware',
    title: 'Historico de maquininhas',
    description: 'Auditoria de uso, movimentacao e manutencao dos dispositivos.',
    requiredRoles: ['operador'],
  },
  {
    path: 'map',
    label: 'Mapa',
    icon: '10',
    section: 'Mapa',
    eyebrow: 'Mapa',
    title: 'Zonas de nao entrega',
    description: 'Controle manual das areas bloqueadas e restricoes operacionais por zona.',
    requiredRoles: ['operador'],
  },
  {
    path: 'history',
    label: 'Historico',
    icon: '11',
    section: 'Historico',
    eyebrow: 'Historico',
    title: 'Historico por dia',
    description: 'Consulta de dias passados com leitura de vendas, fechamento e ocorrencias.',
    requiredRoles: ['operador'],
  },
  {
    path: 'occurrences',
    label: 'Ocorrencias',
    icon: '12',
    section: 'Historico',
    eyebrow: 'Historico',
    title: 'Ocorrencias',
    description: 'Registro e navegacao de ocorrencias operacionais do turno.',
    requiredRoles: ['operador'],
  },
  {
    path: 'analysis',
    label: 'Analise',
    icon: '13',
    section: 'Analise',
    eyebrow: 'Analise',
    title: 'Analise',
    description:
      'Entrada unica da camada analitica, com seletor interno para relatorios e leituras historicas.',
    requiredRoles: ['gerente'],
  },
  {
    path: 'reports',
    label: 'Relatorios',
    icon: '13',
    section: 'Analise',
    eyebrow: 'Analise',
    title: 'Relatorios',
    description: 'Camada analitica principal com indicadores e leitura historica.',
    requiredRoles: ['operador'],
    hiddenInSidebar: true,
  },
  {
    path: 'monthly-report',
    label: 'Rel. mensal',
    icon: '14',
    section: 'Analise',
    eyebrow: 'Analise',
    title: 'Relatorio mensal',
    description: 'Resumo mensal, navegacao por periodo e comparativos de desempenho.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'orders-hour',
    label: 'Pedidos por hora',
    icon: '15',
    section: 'Analise',
    eyebrow: 'Analise',
    title: 'Pedidos por hora',
    description: 'Leitura detalhada de volume por faixa horaria e comportamento do turno.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'ratings',
    label: 'Avaliacoes',
    icon: '16',
    section: 'Analise',
    eyebrow: 'Analise',
    title: 'Avaliacoes',
    description: 'Painel de satisfacao, sinais de experiencia e qualidade de atendimento.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'audit-log',
    label: 'Audit log',
    icon: '17',
    section: 'Sistema',
    eyebrow: 'Sistema',
    title: 'Log de auditoria',
    description: 'Historico de acoes, eventos e rastreabilidade do sistema.',
    requiredRoles: ['admin'],
  },
  {
    path: 'pdv',
    label: 'PDV',
    icon: '18',
    section: 'PDV',
    eyebrow: 'PDV',
    title: 'Central do PDV',
    description:
      'Entrada unica do PDV com atalhos para pedido, venda, catalogo, estoque, clientes e relatorios.',
    requiredRoles: ['atendente'],
  },
  {
    path: 'pos',
    label: 'Novo pedido',
    icon: '18',
    section: 'PDV',
    eyebrow: 'PDV',
    title: 'PDV',
    description: 'Fluxo de montagem de pedido, cliente, itens, frete e finalizacao.',
    requiredRoles: ['atendente'],
    hiddenInSidebar: true,
  },
  {
    path: 'orders',
    label: 'Pedidos',
    icon: '19',
    section: 'PDV',
    eyebrow: 'PDV',
    title: 'Dominio de pedidos',
    description:
      'Pedidos comerciais e operacionais sem impacto definitivo em estoque ou financeiro.',
    requiredRoles: ['atendente'],
    hiddenInSidebar: true,
  },
  {
    path: 'sales',
    label: 'Vendas',
    icon: '20',
    section: 'PDV',
    eyebrow: 'PDV',
    title: 'Dominio de vendas',
    description: 'Vendas reais com postagem de estoque, financeiro e auditoria centralizada.',
    requiredRoles: ['operador'],
    hiddenInSidebar: true,
  },
  {
    path: 'products',
    label: 'Produtos',
    icon: '21',
    section: 'PDV',
    eyebrow: 'Catalogo',
    title: 'Produtos',
    description: 'Catalogo com busca, categorias, ordenacao e edicao operacional.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'inventory',
    label: 'Estoque',
    icon: '22',
    section: 'PDV',
    eyebrow: 'Estoque',
    title: 'Controle de estoque',
    description: 'Saldo atual, ajustes, historico e integracao automatica com as vendas.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'customers',
    label: 'Clientes',
    icon: '23',
    section: 'PDV',
    eyebrow: 'CRM',
    title: 'Clientes',
    description: 'Base de clientes, localizacao, historico e relacionamento com o PDV.',
    requiredRoles: ['atendente'],
    hiddenInSidebar: true,
  },
  {
    path: 'pos-reports',
    label: 'Rel. PDV',
    icon: '24',
    section: 'PDV',
    eyebrow: 'PDV',
    title: 'Relatorios do PDV',
    description: 'Relatorios comerciais, filtros por data e leitura da operacao de vendas.',
    requiredRoles: ['gerente'],
    hiddenInSidebar: true,
  },
  {
    path: 'settings',
    label: 'Configuracoes',
    icon: '25',
    section: 'Sistema',
    eyebrow: 'Sistema',
    title: 'Configuracoes',
    description: 'Preferencias, PIN local, sincronizacao e ajustes do app.',
    requiredRoles: ['admin'],
  },
]

export function getRouteByPathname(pathname) {
  const normalizedPath = pathname.replace(/^\/+/, '')
  const directMatch = routeDefinitions.find((route) => route.path === normalizedPath)

  if (directMatch) {
    return directMatch
  }

  const nestedMatch = routeDefinitions.find((route) => normalizedPath.startsWith(`${route.path}/`))
  return nestedMatch ?? routeDefinitions[0]
}
